Drop Spark event when cannot be serialized
In rare cases, Spark events cannot be serialized.
This happened recently on Databricks:
```
com.fasterxml.jackson.databind.JsonMappingException: Exceeded 2097152 bytes (current = 2100278)
(through reference chain: org.apache.spark.sql.catalyst.expressions.AttributeReference["canonicalized"]->org.apache.spark.s...
...
Caused by: com.databricks.spark.util.LimitedOutputStream$LimitExceededException: Exceeded 2097152 bytes (current = 2100278)
```

It seems to be a known but unaddressed issue:
https://forums.databricks.com/questions/44005/encountering-limitexceededexception-in-a-spark-job.html

In the meantime, we protect the agent against this case.